# Generated by Django 5.0.3 on 2024-03-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='published_date',
        ),
    ]
